### ISSUE TITLE
[Question] Are you interested in self hosting forwardemail

### ISSUE THREAD

**Issue by gc-ss** [politician/barissat-infra#4]
Are you interested in self hosting forwardemail (both SMTP and Web)?

We will start off with ansible playbooks and then Hashistack HashiCorp Terraform/CDK after ansible playbooks are working.

**Comment by politician** [comment]
@gc-ss I chose forwardemail so I can self-host at any time if I want to but right now for the price point ($3/month) I prefer not to.
